version: '3'
services:
  postgres:
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_DB: vendi       # Nome do banco de dados
      POSTGRES_USER: user         # Nome de usuário
      POSTGRES_PASSWORD: 1234       # Senha do usuário
    ports:
      - "5432:5432"                  # Porta do PostgreSQL
    volumes:
      - postgres-data:/var/lib/postgresql/data   # Volume para persistência dos dados
    networks:
      - app-network

  springboot:
    image: vendi
    container_name: vendi
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/vendi
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: 1234
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge
