POST {{base_url}}/category
Authorization: Bearer {{auth_token}}
Content-Type: application/json
Accept: application/json

{
  "name": "Eletronics",
  "description": "Eletronics items"
}

###

GET {{base_url}}/category
Authorization: Bearer {{auth_token}}
Content-Type: application/json
Accept: application/json
