POST {{base_url}}/product
Authorization: Bearer {{auth_token}}
Content-Type: application/json
Accept: application/json

{
  "name": "teste",
  "price": 5,
  "quantity": 4,
  "installment": 0,
  "discount": 0,
  "photosToCreate": [
    {
      "data": "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/wcAAwAB/5YfZUEAAAAASUVORK5CYII=",
      "contentType": "image/png",
      "filename": "example.png",
      "isMainPhoto": false
    },
    {
      "data": "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/wcAAwAB/5YfZUEAAAAASUVORK5CYII=",
      "contentType": "image/png",
      "filename": "example.png",
      "isMainPhoto": false
    },
    {
      "data": "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/wcAAwAB/5YfZUEAAAAASUVORK5CYII=",
      "contentType": "image/png",
      "filename": "example.png",
      "isMainPhoto": false
    },
    {
      "data": "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/wcAAwAB/5YfZUEAAAAASUVORK5CYII=",
      "contentType": "image/png",
      "filename": "example.png",
      "isMainPhoto": false
    },
    {
      "data": "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/wcAAwAB/5YfZUEAAAAASUVORK5CYII=",
      "contentType": "image/png",
      "filename": "example.png",
      "isMainPhoto": true
    }
  ],
  "categoriesIds": ["74e9c28b-275e-418f-bb41-c5e226beab64"]
}

###

PUT {{base_url}}/product/e744ba95-dbbe-4b36-8666-07684b3edbdc
Authorization: Bearer {{auth_token}}
Content-Type: application/json
Accept: application/json

{
  "name": "teste",
  "price": 5,
  "quantity": 4,
  "installment": 0,
  "discount": 0,
  "photosToCreate": [
    {
      "data": "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/wcAAwAB/5YfZUEAAAAASUVORK5CYII=",
      "contentType": "image/png",
      "filename": "example.png",
      "isMainPhoto": false
    },
    {
      "data": "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/wcAAwAB/5YfZUEAAAAASUVORK5CYII=",
      "contentType": "image/png",
      "filename": "example.png",
      "isMainPhoto": false
    },
    {
      "data": "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/wcAAwAB/5YfZUEAAAAASUVORK5CYII=",
      "contentType": "image/png",
      "filename": "example.png",
      "isMainPhoto": false
    },
    {
      "data": "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/wcAAwAB/5YfZUEAAAAASUVORK5CYII=",
      "contentType": "image/png",
      "filename": "example.png",
      "isMainPhoto": false
    },
    {
      "data": "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/wcAAwAB/5YfZUEAAAAASUVORK5CYII=",
      "contentType": "image/png",
      "filename": "example.png",
      "isMainPhoto": true
    }
  ],
  "categoriesIds": ["74e9c28b-275e-418f-bb41-c5e226beab64"]
}

###

GET {{base_url}}/product/user
Authorization: Bearer {{auth_token}}
Content-Type: application/json
Accept: application/json

###

GET {{base_url}}/product?limit=5
Authorization: Bearer {{auth_token}}
Content-Type: application/json
Accept: application/json

###

DELETE {{base_url}}/product/5b68615b-0bd2-4379-93b8-44295e618754
Authorization: Bearer {{auth_token}}
Content-Type: application/json
Accept: application/json

###

GET {{base_url}}/product/7168f589-7d4a-4a72-a1ce-44214409b8be
Authorization: Bearer {{auth_token}}
Content-Type: application/json
Accept: application/json