POST {{base_url}}/product
Authorization: Bearer {{auth_token}}
Content-Type: application/json
Accept: application/json

{
  "name": "teste",
  "price": 5,
  "quantity": 4,
  "installment": 0,
  "discount": 0,
  "photosToCreate": [
    {
      "data": "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/wcAAwAB/5YfZUEAAAAASUVORK5CYII=",
      "contentType": "image/png",
      "filename": "example.png",
      "isMainPhoto": false
    },
    {
      "data": "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/wcAAwAB/5YfZUEAAAAASUVORK5CYII=",
      "contentType": "image/png",
      "filename": "example.png",
      "isMainPhoto": false
    },
    {
      "data": "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/wcAAwAB/5YfZUEAAAAASUVORK5CYII=",
      "contentType": "image/png",
      "filename": "example.png",
      "isMainPhoto": false
    },
    {
      "data": "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/wcAAwAB/5YfZUEAAAAASUVORK5CYII=",
      "contentType": "image/png",
      "filename": "example.png",
      "isMainPhoto": false
    },
    {
      "data": "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/wcAAwAB/5YfZUEAAAAASUVORK5CYII=",
      "contentType": "image/png",
      "filename": "example.png",
      "isMainPhoto": true
    }
  ],
  "categoriesIds": ["95e9d289-5e1d-46f7-8b16-82233ec54ac1"]
}

###

PUT {{base_url}}/product/39d47bf0-8c24-4787-b9e1-380997625394
Authorization: Bearer {{auth_token}}
Content-Type: application/json
Accept: application/json

{
  "name": "teste",
  "price": 5,
  "quantity": 4,
  "installment": 0,
  "discount": 0,
  "photosToCreate": [
    {
      "data": "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/wcAAwAB/5YfZUEAAAAASUVORK5CYII=",
      "contentType": "image/png",
      "filename": "example.png",
      "isMainPhoto": false
    },
    {
      "data": "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/wcAAwAB/5YfZUEAAAAASUVORK5CYII=",
      "contentType": "image/png",
      "filename": "example.png",
      "isMainPhoto": false
    },
    {
      "data": "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/wcAAwAB/5YfZUEAAAAASUVORK5CYII=",
      "contentType": "image/png",
      "filename": "example.png",
      "isMainPhoto": false
    },
    {
      "data": "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/wcAAwAB/5YfZUEAAAAASUVORK5CYII=",
      "contentType": "image/png",
      "filename": "example.png",
      "isMainPhoto": false
    },
    {
      "data": "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/wcAAwAB/5YfZUEAAAAASUVORK5CYII=",
      "contentType": "image/png",
      "filename": "example.png",
      "isMainPhoto": true
    }
  ],
  "photosToKeep": [],
  "categoriesIds": ["fe2739e9-759d-46d5-b408-0999e75f5e77"]
}

###

GET {{base_url}}/product/user
Authorization: Bearer {{auth_token}}
Content-Type: application/json
Accept: application/json

###

GET {{base_url}}/product?limit=5
Authorization: Bearer {{auth_token}}
Content-Type: application/json
Accept: application/json

###

DELETE {{base_url}}/product/5b68615b-0bd2-4379-93b8-44295e618754
Authorization: Bearer {{auth_token}}
Content-Type: application/json
Accept: application/json

###

GET {{base_url}}/product/7168f589-7d4a-4a72-a1ce-44214409b8be
Authorization: Bearer {{auth_token}}
Content-Type: application/json
Accept: application/json