POST {{base_url}}/product
Authorization: Bearer {{auth_token}}
Content-Type: application/json
Accept: application/json

{
  "name": "product",
  "price": 10.5,
  "quantity": 1,
  "installment": 2,
  "discount": 3
}

###

PUT {{base_url}}/product?productId=37e5f9a3-056d-4918-ac3e-b8918f657938
Authorization: Bearer {{auth_token}}
Content-Type: application/json
Accept: application/json

{
  "name": "product"
}

###

GET {{base_url}}/product
Authorization: Bearer {{auth_token}}
Content-Type: application/json
Accept: application/json

###

DELETE {{base_url}}/product?productId=00c7a28d-0a30-4287-999f-b74324afe90d
Authorization: Bearer {{auth_token}}
Content-Type: application/json
Accept: application/json