POST http://localhost:8080/product
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhQHRlc3R0LmNvbSIsImV4cCI6MTc0MjA4MzgwNH0.xSWqaPbmJfZ0WognvDnlidjWWgBGX4LmCF4MnTm1pIk
Content-Type: application/json
Accept: application/json

{
  "name": "product",
  "price": 10.5,
  "quantity": 1,
  "installment": 2,
  "discount": 3
}

###

PUT http://localhost:8080/product?productId=00c7a28d-0a30-4287-999f-b74324afe90d
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhQHRlc3R0LmNvbSIsImV4cCI6MTc0MjA5MTA4Nn0.NbKHa3ujXxXBUXuXF6_IH4KbF8lXXy4qo7wVWllQsos
Content-Type: application/json
Accept: application/json

{
  "name": "product"
}

###

GET http://localhost:8080/product
Authorization: Bearer {{auth_token}}
Content-Type: application/json
Accept: application/json

###

DELETE http://localhost:8080/product?productId=00c7a28d-0a30-4287-999f-b74324afe90d
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhQHRlc3R0LmNvbSIsImV4cCI6MTc0MjA5MTM3OX0.O5m2UevfW3Gw8qQT8XyoRvgi9KtMJWs2VRkwyyx61Bo
Content-Type: application/json
Accept: application/json