POST {{base_url}}/product
Authorization: Bearer {{auth_token}}
Content-Type: application/json
Accept: application/json

{
  "name": "product",
  "price": 10.5,
  "quantity": 1,
  "installment": 2,
  "discount": 3,
  "photos": [{
    "data": "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/wcAAwAB/5YfZUEAAAAASUVORK5CYII=",
    "contentType": "image/png",
    "filename": "example.png"
    }]
}

###

PUT {{base_url}}/product/e744ba95-dbbe-4b36-8666-07684b3edbdc
Authorization: Bearer {{auth_token}}
Content-Type: application/json
Accept: application/json

{
  "name": "product"
}

###

GET {{base_url}}/product
Authorization: Bearer {{auth_token}}
Content-Type: application/json
Accept: application/json

###

DELETE {{base_url}}/product/e744ba95-dbbe-4b36-8666-07684b3edbdc
Authorization: Bearer {{auth_token}}
Content-Type: application/json
Accept: application/json

###

GET {{base_url}}/product/e744ba95-dbbe-4b36-8666-07684b3edbdc
Authorization: Bearer {{auth_token}}
Content-Type: application/json
Accept: application/json