export default (context) => [
  {
    showOn: 'mdAndUp',
    isRouterLink: true,
    to: '/wishlist',
    tooltip: 'Wish List',
    icon: () => (context.wishListActive ? 'mdi-heart' : 'mdi-heart-outline'),
    color: () => (context.wishListActive ? 'golden' : null),
  },
  {
    showOn: 'mdAndUp',
    isRouterLink: true,
    to: '/orders',
    tooltip: 'My Orders',
    icon: 'mdi-shopping-outline',
    color: () => (context.shoppingActive ? 'golden' : null),
  },
  {
    isRouterLink: false,
    icon: 'mdi-cart-outline',
    tooltip: 'Cart',
    color: () => (context.cartActive ? 'golden' : null),
    onClick: () => (context.showCart = !context.showCart),
  },
  {
    showOn: 'mdAndDown',
    isRouterLink: false,
    icon: () => (context.showMenu ? 'mdi-close' : 'mdi-menu'),
    color: () => (context.showMenu ? 'golden' : null),
    onClick: () => (context.showMenu = !context.showMenu),
  },
  {
    showOn: 'mdAndUp',
    isRouterLink: true,
    to: () => (context.isAdmin() ? '/admin' : '/profile'),
    icon: () => (context.isAdmin() ? context.adminIcon : context.accountIcon),
    tooltip: 'My Account',
    color: () => (context.accountActive ? 'golden' : 'black'),
  },
  {
    showOn: 'mdAndUp',
    isRouterLink: true,
    to: '/login',
    tooltip: 'Logout',
    icon: 'mdi-logout',
    color: 'red',
  },
]
