POST {{base_url}}/product
Authorization: Bearer {{auth_token}}
Content-Type: application/json
Accept: application/json

{
  "name": "product",
  "price": 10.5,
  "quantity": 1,
  "installment": 2,
  "discount": 3,
  "photos": [{
    "isMainPhoto": true,
    "data": "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/wcAAwAB/5YfZUEAAAAASUVORK5CYII=",
    "contentType": "image/png",
    "filename": "example.png"
    },
    {
      "data": "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/wcAAwAB/5YfZUEAAAAASUVORK5CYII=",
      "contentType": "image/png",
      "filename": "example.png"
    }]
}

###

PUT {{base_url}}/product/e744ba95-dbbe-4b36-8666-07684b3edbdc
Authorization: Bearer {{auth_token}}
Content-Type: application/json
Accept: application/json

{
  "name": "product"
}

###

GET {{base_url}}/product
Authorization: Bearer {{auth_token}}
Content-Type: application/json
Accept: application/json

###

DELETE {{base_url}}/product/5b68615b-0bd2-4379-93b8-44295e618754
Authorization: Bearer {{auth_token}}
Content-Type: application/json
Accept: application/json

###

GET {{base_url}}/product/7168f589-7d4a-4a72-a1ce-44214409b8be
Authorization: Bearer {{auth_token}}
Content-Type: application/json
Accept: application/json